version: '2'
services:
  directory:
    build: docker/slapd/
    ports:
     - "389:389"
    expose:
     - 389
    environment:
      LDAP_DOMAIN: arkhack.org
      LDAP_ORGANISATION: Arkham Hackerspace
      LDAP_ROOTPASS: cthulhufhtagn
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
    - 5432
  web:
    build: .
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://postgres:postgres@db/postgres"
      KASOWNIK_DEBUG_HOST: "0.0.0.0"
      LDAP_URI: ldap://directory
      LDAP_BIND_DN: cn=admin,dc=arkhack,dc=org
      LDAP_BIND_PASSWORD: cthulhufhtagn
      LDAP_USER_FILTER: ou=People,dc=arkhack,dc=org
      LDAP_STARTTLS: "false"
      BRE_SNAPSHOT_PATH: /code/bresnapshot.sample
    ports:
     - "5000:5000"
    volumes:
     - "./:/code"
